In [62]:
import numpy as np

# Ex 1

# a)

In [63]:
nv = np.zeros(10)
nv[4] = 1
nv


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# b)

In [64]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# c )


In [65]:
y=x[::-1]
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# d)

In [66]:
ar =  np.arange(0, 9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# e)

In [67]:
ar_i = np.array([1,2,0,0,4,0])
np.where(ar_i == 0)[0]

array([2, 3, 5])

# f)

In [68]:
rnd = np.random.random((30))
np.average(rnd)

0.5823207710823303

# g

In [69]:
z = np.ones((6,6))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

# h)


In [70]:
p = np.ones((8,8))
p[1::2,::2] = 0
p[::2,1::2] = 0
p

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# j)

In [71]:
Z = np.arange(11)
Z[2:7] *= -1
print(Z)

[ 0  1 -2 -3 -4 -5 -6  7  8  9 10]


# k)

In [72]:
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.02575595 0.06561392 0.13167642 0.29507636 0.31566197 0.4415566
 0.45006926 0.49522585 0.50366722 0.57552626]


# l)

In [73]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = A == B
print(equal)

[ True  True  True  True False]


# m)

In [74]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.astype('float32') 
print(Z.dtype)

int32
float32



# n)

In [75]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)

D = np.diag(C)
print(D)


[ 18  66 132]


# Ex 2

# a)

In [76]:
class Person(object):
    def __init__(self, firstname, lastname):
        self.firstname = firstname
        self.lastname = lastname
        
    def print_person(self):
        print(self.firstname+' '+self.lastname)

In [77]:
someone = Person('George', 'Sand')
someone.print_person()

George Sand


# b)

In [78]:
class Student(Person):
    def __init__(self, firstname, lastname, subject): 
        Person.__init__(self,firstname, lastname ) 
        self.subject = subject
    def print_student(self):
        print(self.firstname+' '+self.lastname +'\n'+'Subject area: ' + self.subject)
        

In [79]:
some_student = Student('Rosalind', 'Franklin', 'Structure of DNA')
some_student.print_student()

Rosalind Franklin
Subject area: Structure of DNA


# c)

In [80]:
class Teacher(Person):
    def __init__(self, firstname, lastname, course): 
        Person.__init__(self,firstname, lastname ) 
        self.course = course
    def print_teacher(self):
        print(self.firstname+' '+self.lastname +'\n'+'Course of the teacher: ' + self.course)
        

In [81]:
some_teacher = Teacher('Filipe', 'Maia', 'Python programming')
some_teacher.print_teacher()

Filipe Maia
Course of the teacher: Python programming


In [120]:
# Program to multiply two matrices using nested loops
import random

n = 250


def x_gen(N):
    # NxN matrix
    X = np.random.randint(0,100,(N,N))
    return X


def y_gen(N):
    # Nx(N+1) matrix
    Y = np.random.randint(0,100,(N,N+1))
    return Y


def result_gen(N):
    # result is Nx(N+1)
    result = np.zeros((N,N+1))
    return result


def multipl(X,Y,result):

    result=  np.matmul(X,Y)
    return result 


def printing(result):
    for r in result:
        print(r)

x = x_gen(n)
y = y_gen(n)
res = result_gen(n)

result_final = multipl(x, y, res)
printing(result_final)

[598281 645025 557887 641826 586931 604940 614623 564497 642194 603700
 590745 602921 630957 626089 541556 603957 609451 617602 549145 596923
 641475 613006 595997 585069 568305 588839 558123 592125 622076 618937
 604640 573943 598382 614337 568013 572583 575482 598530 644422 557504
 640510 594814 639392 623882 589514 549234 570146 591944 545694 583625
 555931 591134 589776 606876 602297 630384 601081 615385 550599 591352
 593271 582303 607145 593696 599529 622645 540538 574210 614712 625468
 598860 578915 613911 629811 599520 665648 595733 623908 564054 614875
 595475 564376 615705 604893 631442 571957 596383 598093 586799 591810
 622931 583401 555211 561984 594168 604732 621564 615550 591703 612119
 634914 581668 600160 626924 612011 634297 611001 608627 618097 597116
 532031 573088 599829 589968 584384 559717 583925 628661 654344 599147
 618960 582208 598261 585928 617446 582438 582394 567344 536168 589467
 621215 627727 620544 605929 615982 586210 603073 602871 574477 595656
 63132

In [117]:
result_final[0]-result_final[1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [97]:
np.random.randint(0,100,(2,3))

array([[80, 51, 51],
       [61, 34,  7]])

In [104]:
result_final.shape

(25, 26)

In [111]:
result_final[24,:]

array([36712., 63374., 56595., 51445., 49906., 48091., 51253., 41195.,
       51051., 43631., 55111., 52553., 55734., 54833., 45507., 51702.,
       48402., 51994., 60293., 41666., 50174., 53732., 35682., 60280.,
       54516., 47449.])